name: friendly_timezone
description: A friendlier way to show timezones.
version: 0.0.1
author: Hossein Yousefi
repository: https://github.com/HosseinYousefi/friendly_timezone

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter