name: friendly_timezone
description: A friendlier way to show timezones.
version: 0.0.3
author: Hossein Yousefi
repository: https://github.com/HosseinYousefi/friendly_timezone

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies: